export enum Category {
  Aircraft = 'Aircraft',
  AirOperations = 'Air Operations',
  Ships = 'Ships',
  Subs = 'Subs',
  PortOperations = 'Port Operations',
  Weapons = 'Weapons',
  Munitions = 'Munitions',
  CyberIT = 'Cyber/IT',
  Forces = 'Forces',
  PersonnellAdmin = 'Personnell (Admin)',
  Logistics = 'Logistics',
  Fuel = 'Fuel',
  Laydown = 'Laydown',
  Medical = 'Medical',
  FoodWater = 'Food & Water',
  Waste = 'Waste',
  Utilities = 'Utilities',
  Maintenance = 'Maintenance',
  MessingGym = 'Messing / Gym',
  Vehicles = 'Vehicles',
  Berthing = 'Berthing',
  AirfieldOps = 'Airfield Ops',
  ExpeditionaryOps = 'Expeditionary Ops',
  OrdanceWeaponsOps = 'Ordance Weapons Ops',
  WaterfrontOps = 'Waterfront Ops',
  C5ISROps = 'C5ISR Ops',
  LogisticsSupply = 'Logistics & Supply',
  RDTE = 'RDT&E',
  SailorFamilyReadiness = 'Sailor & Family Readiness',
  Training = 'Training',
  InterDepotLevelMaintenance = 'Inter/Depot Level Maintenance',
  BaseSupport = 'Base Support',
}

export const CATEGORIES: Category[] = [
  Category.Aircraft,
  Category.AirOperations,
  Category.Ships,
  Category.Subs,
  Category.PortOperations,
  Category.Weapons,
  Category.Munitions,
  Category.CyberIT,
  Category.Forces,
  Category.PersonnellAdmin,
  Category.Logistics,
  Category.Fuel,
  Category.Laydown,
  Category.Medical,
  Category.FoodWater,
  Category.Waste,
  Category.Utilities,
  Category.Maintenance,
  Category.MessingGym,
  Category.Vehicles,
  Category.Berthing,
  Category.AirfieldOps,
  Category.ExpeditionaryOps,
  Category.OrdanceWeaponsOps,
  Category.WaterfrontOps,
  Category.C5ISROps,
  Category.LogisticsSupply,
  Category.RDTE,
  Category.SailorFamilyReadiness,
  Category.Training,
  Category.InterDepotLevelMaintenance,
  Category.BaseSupport,
  Category.BaseSupport,
]
