export enum Location {
  NSRota = "NS Rota",
  NSANaples = "NSA Naples",
  NASSigonella = "NAS Sigonella",
  NSASoudaBay = "NSA Souda Bay",
  NSFDeveselu = "NSF Deveselu",
  NSFRedzikowo = "NSF Redzikowo",
  Lossiemouth = "Lossiemouth",
  Crombie = "Crombie",
  Keflavik = "Keflavik",
  Grindavik = "Grindavik",
  Evenes = "Evenes",
  Ramsund = "Ramsund",
  USNSELisbon = "USN SE Lisbon",
  USNSEMadrid = "USN SE Madrid",
  USNSEValencia = "USN SE Valencia",
  CampLDijbouti = "Camp L. Djibouti",
  AfricanCSLs = "African CSLs",
  AfricanCL = "African CL",
  NSABahrain = "NSA Bahrain",
  IsaAB = "Isa AB",
  SaaAlNakhl = "Saa Al Nakhl",
  JebAllPort = "Jeb All Port",
  FujairahPort = "Fujairah Port",
  DuqumPort = "Duqum Port",
  MinhadAB = "Minhad AB",
}

export const LOCATIONS: Location[] = [
  Location.NSRota,
  Location.NSANaples,
  Location.NASSigonella,
  Location.NSASoudaBay,
  Location.NSFDeveselu,
  Location.NSFRedzikowo,
  Location.Lossiemouth,
  Location.Crombie,
  Location.Keflavik,
  Location.Grindavik,
  Location.Evenes,
  Location.Ramsund,
  Location.USNSELisbon,
  Location.USNSEMadrid,
  Location.USNSEValencia,
  Location.CampLDijbouti,
  Location.AfricanCSLs,
  Location.AfricanCL,
  Location.NSABahrain,
  Location.IsaAB,
  Location.SaaAlNakhl,
  Location.JebAllPort,
  Location.FujairahPort,
  Location.DuqumPort,
  Location.MinhadAB,
  
]