export const CSV_FIELDS = [
  "Item",
  "Priority",
  "NS Rota",
  "NSA Naples",
  "NAS Sigonella",
  "NSA Souda Bay",
  "NSF Deveselu",
  "NSF Redzikowo",
  "Lossiemouth",
  "Crombie",
  "Keflavik",
  "Grindavik",
  "Evenes",
  "Ramsund",
];
